# Generated by Django 4.0 on 2023-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sancheck', '0004_alter_parktag_num_upvotes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedparks',
            constraint=models.UniqueConstraint(fields=('user_id', 'park_id'), name='unique_favorite'),
        ),
    ]
