# Generated by Django 4.0 on 2023-02-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sancheck', '0005_savedparks_unique_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedparks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to='sancheck.user'),
        ),
    ]
