# Generated by Django 4.0 on 2023-01-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sancheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotetag',
            name='park_id',
        ),
    ]
